use NonZeroU32 for --fuzz (#77)
Current error message:

```
✦ ❯ elm-test-rs --fuzz 0                                                                                                                                  [19:43:07]
Error: Invalid --fuzz argument. It must be >= 1
```

With this change

```
✦ ❯ elm-test-rs --fuzz 0                                                                                                                                  [19:36:53]
Error: Invalid --fuzz value

Caused by:
    number would be zero for non-zero type
```

I am not sure this is a great improvement. I mainly wanted to "make impossible states impossible".